# 一下的配置，有问题
# language: node_js
# node_js:
#   - node
# before_install:
#   - rvm install 2.2.3
# install:
#   - bundle install --path vendor/bundle
#   - npm install -g gulp
#   - npm install
# script:
#   - npm test && gulp build
# services:
#   - mysql
# deploy:
#   provider: heroku
#   api_key:
#     secure: SCkjvrnzmj5g+O8WgEpr59+IdU/aEGmaQnTyfPNXwe14ZdvWSTac5rVESY4Rm3NP+MNX/ZED92NELcUbqNpHpU/Z+RGrHWYMJppJecRXdUuxyII2lfQxCqakf9HegXAMGpizFKLeaP81PILwaOczHpz4PpOslkOanMu7XHrszss1q+0Ty+cwlz0i6pFMHk265GGA+I8YxnkuZbXolyhz/gCoTs2asOnX0gjjv93YaMieLWarNELv7rYwzCtt4QRBzlcD6rUhx0IIblEIUh1FvnJeiDzjlq1qvaWB5513lucHhxRc0FefD37iFVz1BNh286LMk5LZXE2j3tQ6gi/TXL/qyh85biePy1/Iu3saarVQc3NY4g4zHldwcKd6bgcMlUkjpDdtPHMutR6hZG7kwz/4FoATftrQkS6xkY072ibUB3fzkBpWdt5BAsRI6RiQL/JIBZfS1ks4GXjxublGsZw7HYqTUxzCiDzzgtrE7U8YbCgflgODt5/Q3a/q6Oqzpo+qFf1JxUlGV/91Vwmp9nWFlOjU78c2n2BgYteVH2cqmhIPkhNUnTC1jwbEaB5xXibgvGRzHoM7NL8sxtg8zNvt+LHSnpc7B1NqTvLV/JuzMjZbrNL/8whVnz1223CpWo60v2UMSjzDRgKsD4wc1NFXaLFpmTucXOIPPRSFByg=
#   app:
#     staging: ilearnc-staging
#     master: ilearnc-prod
#   skip_cleanup: true
#   run:
#     - bundle exec rake db:migrate
#     - restart
#   on:
#       branch:
#         - staging
#         - production

language: ruby
rvm:
  - 2.2.3

env:
  - TRAVIS_NODE_VERSION="4"

services:
  - mysql

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - bundle install --path vendor/bundle

before_script:
  - mysql -e 'create database ILearnC_test;' -uroot
  - bundle install
  - npm install -g gulp
  - npm install

script:
  # - bundle exec rake spec
  - npm test && gulp build

# 以下配置为deploy 到heroku 上的， 目前使用手动部署
# deploy:
#   provider: heroku
#   api_key:
#     secure: m8/mM2sfUFto+Ub0rRyoKfN2kZ30UWNRi7PLmKPtm6i2fx1aWUrz+Pb+n8Cu0EpTRGraz7LsFFSnNfpVzV0/JpX6z2ERi2CVcIMUnAgnEbQKwzDRrk6G0vTUVsW4KMYik+j/RDARcKto1h+fmRXFsopdF7uZ30NxsoGCBJ6MXqPB3016io5uuQEcMhKZ6JpCm0neLBp5znCYwIi1XxntMWacdSH3P/6C/ARZ1lFGgGwQDHbNJVXBs65FntzbzgaEUkOZuZB8CH+g54XE/FKWsPYWPlzXeajWPbLRoW0OH5hQOheIvlsJqKhQjoFZJg70+mcb0nsNEQaUXC8nvJTT+e7d+oI95fKP3uDykGLugVk0nRNFkzpZRt3cNVx9rZnPmrw/3ei1gOq8iTVrcKWkKTSjk+kGgoYwJYvfUquYVk1711l2bk06gRb04yPToKwik5lccybAxyjEHjMZJTloVa9HUJDpc4fhKohJ7x/lEktVw69pOJXbqxOJcv4ZubwpI8xC4f98zObyBCTtZn8JzvmRl1F8AO2cP1a0IsLY53R6IzZcFfDl26BhPSDut1bfMNUhMgG56aoZcf6hxc0H8pEzL2yHb025HT90NJuRLK6bvUE10cADDK0Xfodmb2ZqnmNiu6NNIcdHNCjDW3VVc9rposQBFWwl4vJmKS+0rX8=
#   app:
#     staging: ilearnc-staging
#     master: ilearnc-prod
#   run:
#     - "rake db:migrate db:seed"
#     - "rake assets:precompile"
    # - bundle exec rake db:migrate
