language: node_js
node_js:
  - node
before_install:
  - rvm install 2.2.3
install:
  - bundle install --path vendor/bundle
  - npm install -g gulp
  - npm install
script:
  - npm test && gulp build
services:
  - mysql
deploy:
  provider: heroku
  api_key:
    secure: SCkjvrnzmj5g+O8WgEpr59+IdU/aEGmaQnTyfPNXwe14ZdvWSTac5rVESY4Rm3NP+MNX/ZED92NELcUbqNpHpU/Z+RGrHWYMJppJecRXdUuxyII2lfQxCqakf9HegXAMGpizFKLeaP81PILwaOczHpz4PpOslkOanMu7XHrszss1q+0Ty+cwlz0i6pFMHk265GGA+I8YxnkuZbXolyhz/gCoTs2asOnX0gjjv93YaMieLWarNELv7rYwzCtt4QRBzlcD6rUhx0IIblEIUh1FvnJeiDzjlq1qvaWB5513lucHhxRc0FefD37iFVz1BNh286LMk5LZXE2j3tQ6gi/TXL/qyh85biePy1/Iu3saarVQc3NY4g4zHldwcKd6bgcMlUkjpDdtPHMutR6hZG7kwz/4FoATftrQkS6xkY072ibUB3fzkBpWdt5BAsRI6RiQL/JIBZfS1ks4GXjxublGsZw7HYqTUxzCiDzzgtrE7U8YbCgflgODt5/Q3a/q6Oqzpo+qFf1JxUlGV/91Vwmp9nWFlOjU78c2n2BgYteVH2cqmhIPkhNUnTC1jwbEaB5xXibgvGRzHoM7NL8sxtg8zNvt+LHSnpc7B1NqTvLV/JuzMjZbrNL/8whVnz1223CpWo60v2UMSjzDRgKsD4wc1NFXaLFpmTucXOIPPRSFByg=
  app:
    staging: ilearnc-staging
    master: ilearnc-prod
  skip_cleanup: true
  run:
    - bundle exec rake db:migrate
    - restart
  on:
      branch:
        - staging
        - production

